name: Deploy to GitHub pages

on:
  push:
    # this might change depending on whether you are publishing a site for a normal repo or a user/organization repo
    branches: [ main ]

jobs:
  build:
    # runs-on: ubuntu-latest

    steps:
    - uses: jenkey2011/vuepress-deploy@v1.8.1
    - run: | 
      cd vuepress
      yarn build
