name: Build Eleventy

on:
  push: 
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - name: Eleventy Action
        uses: TartanLlama/actions-eleventy@master
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: _site 
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # Arguments to pass to the Eleventy invocation
          args: # optional
          # If set to `true`, `npm install` will be run before Eleventy is invoked
          install_dependencies: true
